name: scrape reddit

on:
  schedule:
    # - cron: '55 5 * * *' # every day at 5:55am
    - cron: '59 6 30 2 *' # every 30th of February at 6:59am
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python     
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python 
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"


      #----------------------------------------------
      # --------    install creds    -------   
      #----------------------------------------------
      - name: Install creds
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      #----------------------------------------------
      #  -----  install & configure poetry  -----      
      #----------------------------------------------
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.3

        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      #----------------------------------------------
      # --------    install dependencies    -------   
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --no-dev
      #----------------------------------------------
      # run scrape
      #----------------------------------------------       
      - name: Scrape
        run: |
          source .venv/bin/activate
          poetry run python -c 'import os;print(os.environ)'
          poetry run python scrape_reddit.py
        env:
          SUBREDDIT: 'wallstreetbets'
          NUM_PAGES: 3
          # The number of pages to scrape from the subreddit. Each page contains 25 posts. 
          # Defaults to 3, resulting in 75 posts (before filtering).
          MIN_NR_COMMENTS: 10
          # The minimum number of comments a post must have to be included.


      #----------------------------------------------
      # publish to github
      #----------------------------------------------
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
